###
GET http://localhost:3000/api/v1/quiz

###
POST http://localhost:3000/api/v1/quiz
Content-Type: application/json

{
    "question": "test soal",
    "multiple_choice": ["1", "2", "3", "4", "5"],
    "correct_answer": "1",
    "package": "64e829a3dcd2bcda9794ea57"
}