###
GET http://localhost:3000/api/v1/reset
Authorization: Basic superadmin21:superadmin21

###
GET http://localhost:3000/api/v1/reset/packages
Authorization: Basic superadmin21:superadmin21

###
GET http://localhost:3000/api/v1/reset/quizzes
Authorization: Basic superadmin21:superadmin21

###
GET http://localhost:3000/api/v1/reset/userprogresses
Authorization: Basic superadmin21:superadmin21